# Site
title:              meowstations
bio:                "Hi! I'm Silvia Gaetano, a freelance Social Media Manager and Translator with a background in Computer Science and Transcultural Communication. Please feel free to have a look at my projects and contact me at the channels below, should you require services in Social Media Management, Community Management, Translation and Editing."
description:        "Multipotentialite with a passion for Technology, Languages, Social Media and Video Games."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://meowstations.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            meowstations
facebook:           meowstations
github:             meowstations
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           SilviaGaetano
#xing:              username
instagram:          meowstations
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              meowstations
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
